package org.rcsb.strucmotif.update;

class Demo {
    public static void main(String[] args) {
        // perform a full load of all structures in RCSB PDB with default configuration
        StrucmotifUpdate.main(new String[] { "ADD",
        "3TOY",
        "3CB3",
        "3OZY",
        "4DWD",
        "2QQ6",
        "2P0I",
        "1TZZ",
        "3P3B",
        "3D47",
        "2HXT",
        "3H12",
        "2HNE",
        "2GDQ",
        "2QGY",
        "4A35",
        "3OP2",
        "1ZDM",
        "4IP4",
        "3CK5",
        "3UXL",
        "4X2P",
        "3UXK",
        "4FP1",
        "5XD7",
        "3GO2",
        "4GGB",
        "2PP1",
        "4IP5",
        "4JN8",
        "3TCS",
        "3UGV",
        "3OPS",
        "3RR1",
        "4H83",
        "3SN4",
        "3V5C",
        "3TTE",
        "3MSY",
        "5OLC",
        "3D46",
        "2HXU",
        "1MDR",
        "2PP3",
        "2OVL",
        "1MNS",
        "3SN0",
        "6TNE",
        "3N4E",
        "2POZ",
        "2GGE",
        "3V5F",
        "3EKG",
        "4HPN",
        "3RRA",
        "2P3Z",
        "3N4F",
        "2OO6",
        "3FXG",
        "2NQL",
        "3U4F",
        "2OZ3",
        "4M6U",
        "3SN1",
        "5XD8",
        "4H1Z",
        "3VCC",
        "4HNC",
        "3QPE",
        "3T9P",
        "4DN1",
        "2PPG",
        "1YEY",
        "3OZM",
        "2HZG",
        "2OG9",
        "4H19",
        "4KEM",
        "3CXO",
        "2I5Q",
        "3BJS",
        "6VIM",
        "3CYJ",
        "3BOX",
        "4JN7",
        "2MNR",
        "1MRA",
        "3TJ4",
        "2GSH",
        "1DTN",
        "3NO1",
        "2PP0",
        "3T8Q",
        "3SJN",
        "2DW6",
        "1MDL",
        "2DW7" });

        // load some arbitrary (external) structure data like AlphaFold models
        // TODO these won't actually work, support them and/or choose better examples
//        StrucmotifUpdate.main(new String[] {
//                "ADD",
//                "AF-Q76EI6-F1,https://alphafold.ebi.ac.uk/files/AF-Q76EI6-F1-model_v1.cif",
//                "AF-Q8W3K0-F1,https://alphafold.ebi.ac.uk/files/AF-Q8W3K0-F1-model_v1.cif",
//                "AF-Q9CPN9-F1,https://alphafold.ebi.ac.uk/files/AF-Q9CPN9-F1-model_v1.cif",
//                "AF-P07477-F1,https://alphafold.ebi.ac.uk/files/AF-P07477-F1-model_v1.cif",
//                "AF-Q8NHM4-F1,https://alphafold.ebi.ac.uk/files/AF-Q8NHM4-F1-model_v1.cif",
//                "MA-9Z55Z,file:///Users/sebastian/Downloads/ma-9z55z.cif",
//                "MA-AGHOX,file:///Users/sebastian/Downloads/ma-aghox.cif"
//        });
    }
}